import test from 'node:test';
import assert from 'node:assert/strict';
import {quote,parseCsv,exportCsv} from './rfq.mjs';
const cat=[{sku:'SW-01',description:'Switch',unit:'EA',unit_price:'12.50',currency:'EUR'}];
const line={sku:'SW-01',description:'Switch',quantity:'3',unit:'EA'};
const q=(rows=[line],catalogue=cat)=>quote(rows,catalogue);
test('matched approved catalogue price',()=>assert.equal(q().total,'37.50'));
test('incoming price never overrides catalogue',()=>assert.equal(q([{...line,unit_price:'0.01'}]).rows[0].approved_price,'12.50'));
test('unknown product blocks complete quote',()=>assert.equal(q([{...line,sku:'NOPE'}]).total,null));
test('unit mismatch needs review',()=>assert.match(q([{...line,unit:'BOX'}]).exceptions[0].reason,/unit_mismatch/));
test('invalid quantity needs review',()=>assert.match(q([{...line,quantity:'-3'}]).exceptions[0].reason,/invalid_quantity/));
test('duplicate catalogue code needs review',()=>assert.match(q([line],[...cat,...cat]).exceptions[0].reason,/duplicate_catalogue/));
test('duplicate quote line needs review',()=>assert.match(q([line,{...line}]).exceptions[0].reason,/duplicate_rfq/));
test('invalid approved price blocked',()=>assert.match(q([line],[{...cat[0],unit_price:'N/A'}]).exceptions[0].reason,/invalid_approved_price/));
test('mixed currencies block total',()=>assert.equal(q([line,{...line,sku:'B'}],[...cat,{sku:'B',description:'Cable',unit:'EA',unit_price:'4.00',currency:'USD'}]).total,null));
test('quoted multiline CSV is parsed',()=>assert.equal(parseCsv('name,msg\nA,"Some ""quoted""\ntext"\n')[0].msg,'Some "quoted"\ntext'));
test('bad quoted CSV rejected',()=>assert.throws(()=>parseCsv('a,b\n1,"oops'),/Unclosed/));
test('formula injection escaped',()=>assert.match(exportCsv([{a:'=1+2'}],['a']),/"'=1\+2"/));
test('CSV roundtrip',()=>assert.equal(parseCsv(exportCsv(q().rows))[0].amount,'37.50'));
test('empty RFQ is not complete',()=>assert.equal(q([]).total,null));
test('missing fields fail closed',()=>assert.throws(()=>q([{sku:'SW-01'}]),/Missing fields/));
